# Generated by Django 4.2.6 on 2023-10-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_account_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='new_login_ip_notification',
            field=models.CharField(default='False', max_length=255),
        ),
    ]
