# Generated by Django 4.2.6 on 2023-11-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_new_login_ip_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
