# Generated by Django 4.2.6 on 2023-11-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_email_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login_ip',
            field=models.CharField(max_length=255),
        ),
    ]
