# Generated by Django 4.2.6 on 2023-11-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_last_login_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='John', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='regist_date',
            field=models.DateField(default='2023-11-01'),
        ),
    ]
